#!/bin/bash

docker manifest create docker.io/nimbix/lxcfs:latest \
    docker.io/nimbix/lxcfs:latest-amd64 \
    docker.io/nimbix/lxcfs:latest-ppc64le
docker manifest push docker.io/nimbix/lxcfs:latest

