#!/bin/bash

LXCFS_VERSION=3.0.3
[ -n "$1" ] && LXCFS_VERSION="$1"

docker manifest create docker.io/nimbix/lxcfs:$LXCFS_VERSION \
    docker.io/nimbix/lxcfs:$LXCFS_VERSION-amd64 \
    docker.io/nimbix/lxcfs:$LXCFS_VERSION-ppc64le
docker manifest push docker.io/nimbix/lxcfs:$LXCFS_VERSION

docker manifest create docker.io/nimbix/lxcfs:latest \
    docker.io/nimbix/lxcfs:latest-amd64 \
    docker.io/nimbix/lxcfs:latest-ppc64le
docker manifest push docker.io/nimbix/lxcfs:latest

