apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: lxcfs
  namespace: kube-system
  labels:
    app: lxcfs
spec:
  selector:
    matchLabels:
      app: lxcfs
  template:
    metadata:
      labels:
        app: lxcfs
    spec:
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: lxcfs
        image: docker.io/nimbix/lxcfs:3.0.3-2
        imagePullPolicy: Always
        env:
          - name: HOST_LXCFS_DIR
            value: "/var/lib/lxcfs"
          - name: HOST_LXCFS_INSTALL_DIR
            value: "/usr/local/lxcfs-daemonset"
        securityContext:
          privileged: true
        volumeMounts:
        - name: rootfs
          mountPath: /host
      volumes:
      - name: rootfs
        hostPath:
          path: /
